// const adds = require('./add_Module');
// require('./batman');
// require('./superman');
// require('./iife');
const SuperHero = require('./super-hero');
// console.log("'aka' first node hello");
// console.log(adds(1, 100));
const superHero = new SuperHero('alisher');
console.log(superHero.name);
superHero.name = ' ..somthing ';
console.log(superHero.name);
